# pappenheim

samplesheet: "NA"
rundir: "NA"
reference: "~/pappenheim/primer_schemes/ONT-Midnight-nCoV-2019/V1/ONT-Midnight-nCoV-2019.reference.fasta"
regions: "~/pappenheim/primer_schemes/ONT-Midnight-nCoV-2019/V1/ONT-Midnight-nCoV-2019.insert.bed"
threshold: 20
maxDepth: 400
run_monitoring: False

# pappenheim-reciever

blacklisted_samples_file: "blacklisted_samples.tsv"

mads_output_obey_quality_control: "TRUE" # Can be set to "FALSE" with ' --config mads_output_obey_quality_control="FALSE" ' on the command line.
clean_dir: "../BACKUP/nanopore_sarscov2/pappenheim_clean"
