#name: pappenheim1
channels:
  - bioconda
  - conda-forge
dependencies:
  - snakemake
  - jinja2
  - networkx
  - matplotlib
  - graphviz
  - pysam
  - pyyaml
  - pandas
  - pip
  - pip:
    - pandas_ods_reader
    - xlrd # for xls
    - openpyxl # for xlsx